/**
 * GENERATED by .superpowers/sprite-register.mjs — do not hand-edit.
 * Frame pixel space: y down from the frame top; the feet line is the frame
 * bottom; `anchor` is the clasped-fist cluster (string attachment).
 * STAND_H is the standing reference height all frames are scaled against.
 */

export interface SpriteFrame {
  name: string
  w: number
  h: number
  anchorX: number
  anchorY: number
}

export const SPRITE_STAND_H = 900

export const SPRITE_FRAMES: readonly SpriteFrame[] = [
  {
    "name": "walk_01",
    "w": 788,
    "h": 900,
    "anchorX": 159,
    "anchorY": 545
  },
  {
    "name": "walk_02",
    "w": 781,
    "h": 900,
    "anchorX": 177,
    "anchorY": 558
  },
  {
    "name": "walk_03",
    "w": 870,
    "h": 900,
    "anchorX": 229,
    "anchorY": 546
  },
  {
    "name": "walk_04",
    "w": 910,
    "h": 900,
    "anchorX": 243,
    "anchorY": 528
  },
  {
    "name": "walk_05",
    "w": 791,
    "h": 900,
    "anchorX": 169,
    "anchorY": 504
  },
  {
    "name": "walk_06",
    "w": 814,
    "h": 900,
    "anchorX": 181,
    "anchorY": 540
  },
  {
    "name": "walk_07",
    "w": 876,
    "h": 900,
    "anchorX": 261,
    "anchorY": 509
  },
  {
    "name": "walk_08",
    "w": 867,
    "h": 900,
    "anchorX": 228,
    "anchorY": 526
  },
  {
    "name": "strain_01",
    "w": 956,
    "h": 780,
    "anchorX": 253,
    "anchorY": 415
  },
  {
    "name": "strain_02",
    "w": 966,
    "h": 780,
    "anchorX": 251,
    "anchorY": 407
  },
  {
    "name": "strain_03",
    "w": 927,
    "h": 780,
    "anchorX": 275,
    "anchorY": 414
  },
  {
    "name": "hold_01",
    "w": 617,
    "h": 930,
    "anchorX": 44,
    "anchorY": 550
  },
  {
    "name": "hold_02",
    "w": 522,
    "h": 930,
    "anchorX": 55,
    "anchorY": 525
  }
] as const

export const SPRITE_WALK = SPRITE_FRAMES.slice(0, 8)
export const SPRITE_STRAIN = SPRITE_FRAMES.slice(8, 11)
export const SPRITE_HOLD = SPRITE_FRAMES.slice(11, 13)
